#!/usr/bin/env python3
"""Generate a GRIT .grd that packs the prebuilt Stead sidebar WebUI bundle.

The SvelteKit SPA produces hash-named files under _app/, so we can't hand-write
a static resource list. This walks the installed bundle directory and emits a
.grd with one <include> per file plus the resource-map outputs that
webui::SetupWebUIDataSource() consumes.

Usage: gen_sidebar_grd.py <bundle_dir> <out_grd_path>

  <bundle_dir>   directory holding index.html + _app/... (the copied bundle)
  <out_grd_path> .grd to write (lives next to the files; <include file=...>
                 paths are relative to the .grd's directory)
"""
import os
import sys
import re


def idr_name(rel_path: str) -> str:
    """A valid C identifier for a resource, e.g. _app/immutable/x.js ->
    IDR_STEAD_SIDEBAR__APP_IMMUTABLE_X_JS."""
    ident = re.sub(r'[^A-Za-z0-9]', '_', rel_path).upper()
    return f'IDR_STEAD_SIDEBAR_{ident}'


def main() -> int:
    if len(sys.argv) != 3:
        sys.stderr.write(__doc__)
        return 2
    bundle_dir, out_grd = sys.argv[1], sys.argv[2]
    grd_dir = os.path.dirname(os.path.abspath(out_grd))
    out_grd_abs = os.path.abspath(out_grd)

    files = []
    for root, _, names in os.walk(bundle_dir):
        for name in names:
            abs_path = os.path.join(root, name)
            if name == 'BUILD.gn' or os.path.abspath(abs_path) == out_grd_abs:
                continue
            # Path as served under the WebUI host (and the grit map key).
            rel = os.path.relpath(abs_path, bundle_dir).replace(os.sep, '/')
            # Path grit reads from, relative to the .grd location.
            file_attr = os.path.relpath(abs_path, grd_dir).replace(os.sep, '/')
            files.append((rel, file_attr))
    files.sort()

    if not any(rel == 'index.html' for rel, _ in files):
        sys.stderr.write(f'error: no index.html in {bundle_dir}\n')
        return 1

    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        '<!-- GENERATED by resources/stead/gen_sidebar_grd.py - do not edit. -->',
        '<grit latest_public_release="0" current_release="1">',
        '  <outputs>',
        '    <output filename="grit/stead_sidebar_resources.h" type="rc_header">',
        "      <emit emit_type='prepend'></emit>",
        '    </output>',
        '    <output filename="grit/stead_sidebar_resources_map.cc" '
        'type="resource_file_map_source" />',
        '    <output filename="grit/stead_sidebar_resources_map.h" '
        'type="resource_map_header" />',
        '    <output filename="stead_sidebar_resources.pak" type="data_package" />',
        '  </outputs>',
        '  <release seq="1">',
        '    <includes>',
    ]
    for rel, file_attr in files:
        lines.append(
            f'      <include name="{idr_name(rel)}" '
            f'file="{file_attr}" resource_path="{rel}" '
            f'type="BINDATA" />'
        )
    generated_mojo_files = [
        (
            'IDR_STEAD_SIDEBAR_AGENT_CONTROL_MOJOM_WEBUI_JS',
            '${root_gen_dir}/chrome/browser/resources/stead_sidebar/tsc/'
            'chrome/browser/ui/stead/agent_control/'
            'agent_control.mojom-webui.js',
            'agent_control.mojom-webui.js',
        ),
        (
            'IDR_STEAD_SIDEBAR_BRAIN_CONSOLE_MOJOM_WEBUI_JS',
            '${root_gen_dir}/chrome/browser/resources/stead_sidebar/tsc/'
            'chrome/browser/ui/stead/brain/brain_console.mojom-webui.js',
            'brain_console.mojom-webui.js',
        ),
    ]
    for name, file_attr, rel in generated_mojo_files:
        lines.append(
            f'      <include name="{name}" file="{file_attr}" '
            f'resource_path="{rel}" type="chrome_html" />'
        )
    lines += [
        '    </includes>',
        '  </release>',
        '</grit>',
        '',
    ]

    with open(out_grd, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    print(f'wrote {out_grd} ({len(files)} resources)')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
